source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimpleCalc_Example', :exclusive => true do
  pod 'SimpleCalc', :path => '../'
end

target 'SimpleCalc_Tests', :exclusive => true do
  pod 'SimpleCalc', :path => '../'

  
end
